apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: import-https-url-definitions 
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 8Gi
    limits:
      cpu: 2
      memory: 8Gi
  rabbitmq:
    additionalConfig: |
      definitions.import_backend = https
      definitions.https.url = https://raw.githubusercontent.com/rabbitmq/sample-configs/main/queues/1k-quorum-queues.json
      definitions.tls.versions.1 = tlsv1.2
      queue_leader_locator = balanced
